apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: codeinsight
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root123
  MYSQL_DATABASE: codeinsight_ai
  MYSQL_USER: codeinsight
  MYSQL_PASSWORD: codeinsight123