apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: codeinsight

spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:

      imagePullSecrets:
        - name: ecr-secret

      containers:
        - name: user-service

          image: 888635225328.dkr.ecr.us-east-1.amazonaws.com/codeinsight-user-service:latest

          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: codeinsight

spec:
  selector:
    app: user-service

  ports:
    - port: 5000
      targetPort: 5000